"""add ai token category

Revision ID: a05812811a65
Revises: cdb7eda7831c
Create Date: 2026-08-28 00:09:15.699581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05812811a65'
down_revision: Union[str, Sequence[str], None] = 'cdb7eda7831c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('token_category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'token_category')
    # ### end Alembic commands ###
