"""add usage event idempotency key

Revision ID: cdb7eda7831c
Revises: 01e53c897eb6
Create Date: 2026-08-26 18:51:09.897583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb7eda7831c'
down_revision: Union[str, Sequence[str], None] = '01e53c897eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('idempotency_key', sa.Text(), nullable=False))
    op.create_unique_constraint('uq_usage_events_tenant_idempotency', 'usage_events', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_events_tenant_idempotency', 'usage_events', type_='unique')
    op.drop_column('usage_events', 'idempotency_key')
    # ### end Alembic commands ###
