"""replace stripe ids with razorpay ids

Revision ID: e33ad9cc5acb
Revises: a05812811a65
Create Date: 2026-08-30 15:31:10.092343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33ad9cc5acb'
down_revision: Union[str, Sequence[str], None] = 'a05812811a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('razorpay_plan_id', sa.Text(), nullable=True))
    op.drop_column('plans', 'stripe_price_id')
    op.add_column('processed_webhook_events', sa.Column('razorpay_event_id', sa.Text(), nullable=False))
    op.drop_column('processed_webhook_events', 'stripe_event_id')
    op.add_column('subscriptions', sa.Column('razorpay_subscription_id', sa.Text(), nullable=True))
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['razorpay_subscription_id'])
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.add_column('tenants', sa.Column('razorpay_customer_id', sa.Text(), nullable=True))
    op.drop_constraint(op.f('tenants_stripe_customer_id_key'), 'tenants', type_='unique')
    op.create_unique_constraint(None, 'tenants', ['razorpay_customer_id'])
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_unique_constraint(op.f('tenants_stripe_customer_id_key'), 'tenants', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'razorpay_customer_id')
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'razorpay_subscription_id')
    op.add_column('processed_webhook_events', sa.Column('stripe_event_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('processed_webhook_events', 'razorpay_event_id')
    op.add_column('plans', sa.Column('stripe_price_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('plans', 'razorpay_plan_id')
    # ### end Alembic commands ###
